# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
#permalink:           pretty
#relative_permalinks: true
# Setup
title:               'Murod S. Bahovadinov'
tagline:             'Condensed Matter Numerics'
description:         " Q"
url:                 mbakhov.github.io 
baseurl:             ''
paginate:            5
permalink:           pretty
#plugins:
#  - jekyll-paginate
encoding:            UTF-8

# About/contact
author:
  name:              Murod S. Bahovadinov
 url:                mbakhov.github.io/b/
  email:             mbakhovadinov@hse.ru

# Custom vars
version:             1.0.0
